namespace ZambeziDigital.Base.Accounting.Statics;

public partial class Codes
{
        public static readonly List<UnitsOfMeasure> UnitsOfMeasures = new List<UnitsOfMeasure>
    {
        new UnitsOfMeasure { Code = "4B", Id = 1, Name = "Pair", Description = "Pair" },
        new UnitsOfMeasure { Code = "AV", Id = 2, Name = "Cap", Description = "Cap" },
        new UnitsOfMeasure { Code = "BA", Id = 3, Name = "Barrel", Description = "Barrel" },
        new UnitsOfMeasure { Code = "BE", Id = 4, Name = "bundle", Description = "bundle" },
        new UnitsOfMeasure { Code = "BG", Id = 5, Name = "bag", Description = "bag" },
        new UnitsOfMeasure { Code = "BL", Id = 6, Name = "block", Description = "block" },
        new UnitsOfMeasure
        {
            Code = "BLL", Id = 7, Name = "Barrel (petroleum) (158,987 dm3)",
            Description = "Barrel (petroleum) (158,987 dm3)"
        },
        new UnitsOfMeasure { Code = "BX", Id = 8, Name = "box", Description = "box" },
        new UnitsOfMeasure { Code = "CA", Id = 9, Name = "Can", Description = "Can" },
        new UnitsOfMeasure { Code = "CEL", Id = 10, Name = "Cell", Description = "Cell" },
        new UnitsOfMeasure { Code = "CMT", Id = 11, Name = "centimetre", Description = "centimetre" },
        new UnitsOfMeasure { Code = "CR", Id = 12, Name = "CARAT", Description = "CARAT" },
        new UnitsOfMeasure { Code = "DR", Id = 13, Name = "Drum", Description = "Drum" },
        new UnitsOfMeasure { Code = "DZ", Id = 14, Name = "Dozen", Description = "Dozen" },
        new UnitsOfMeasure { Code = "GLL", Id = 15, Name = "Gallon", Description = "Gallon" },
        new UnitsOfMeasure { Code = "GRM", Id = 16, Name = "Gram", Description = "Gram" },
        new UnitsOfMeasure { Code = "GRO", Id = 17, Name = "Gross", Description = "Gross" },

        new UnitsOfMeasure { Code = "KG", Id = 18, Name = "Kilo-Gramme", Description = "Kilo-Gramme" },
        new UnitsOfMeasure { Code = "KTM", Id = 19, Name = "kilometre", Description = "kilometre" },
        new UnitsOfMeasure { Code = "KWT", Id = 20, Name = "kilowatt", Description = "kilowatt" },
        new UnitsOfMeasure { Code = "L", Id = 21, Name = "Litre", Description = "Litre" },
        new UnitsOfMeasure { Code = "LBR", Id = 22, Name = "pound", Description = "pound" },
        new UnitsOfMeasure { Code = "LK", Id = 23, Name = "link", Description = "link" },
        new UnitsOfMeasure { Code = "LTR", Id = 24, Name = "Litre", Description = "Litre" },
        new UnitsOfMeasure { Code = "M", Id = 25, Name = "Metre", Description = "Metre" },
        new UnitsOfMeasure { Code = "M2", Id = 26, Name = "Square Metre", Description = "Square Metre" },
        new UnitsOfMeasure { Code = "M3", Id = 27, Name = "Cubic Metre", Description = "Cubic Metre" },
        new UnitsOfMeasure { Code = "MGM", Id = 28, Name = "milligram", Description = "milligram" },
        new UnitsOfMeasure { Code = "MTR", Id = 29, Name = "metre", Description = "metre" },
        new UnitsOfMeasure
            { Code = "MWT", Id = 30, Name = "megawatt hour (1000 kW.h)", Description = "megawatt hour (1000 kW.h)" },
        new UnitsOfMeasure { Code = "NO", Id = 31, Name = "Number", Description = "Number" },
        new UnitsOfMeasure { Code = "NX", Id = 32, Name = "part per thousand", Description = "part per thousand" },

        new UnitsOfMeasure { Code = "PA", Id = 33, Name = "packet", Description = "packet" },
        new UnitsOfMeasure { Code = "PG", Id = 34, Name = "plate", Description = "plate" },
        new UnitsOfMeasure { Code = "PR", Id = 35, Name = "pair", Description = "pair" },
        new UnitsOfMeasure { Code = "RL", Id = 36, Name = "reel", Description = "reel" },
        new UnitsOfMeasure { Code = "RO", Id = 37, Name = "roll", Description = "roll" },
        new UnitsOfMeasure { Code = "SET", Id = 38, Name = "set", Description = "set" },
        new UnitsOfMeasure { Code = "ST", Id = 39, Name = "sheet", Description = "sheet" },
        new UnitsOfMeasure { Code = "TNE", Id = 40, Name = "tonne (metric ton)", Description = "tonne (metric ton)" },
        new UnitsOfMeasure { Code = "TU", Id = 41, Name = "tube", Description = "tube" },
        new UnitsOfMeasure { Code = "U", Id = 42, Name = "Pieces/item [Number]", Description = "Pieces/item [Number]" },
        new UnitsOfMeasure { Code = "YRD", Id = 43, Name = "yard", Description = "yard" },
        new UnitsOfMeasure { Code = "P1", Id = 44, Name = "Pack", Description = "Pack" },
        new UnitsOfMeasure { Code = "PL", Id = 53, Name = "Pallet", Description = "Pallet" },
        new UnitsOfMeasure { Code = "Ft", Id = 63, Name = "Feet", Description = "Feet" },
        new UnitsOfMeasure { Code = "MM", Id = 64, Name = "Millimetre", Description = "Millimetre" },
        new UnitsOfMeasure { Code = "In", Id = 65, Name = "Inches", Description = "Inches" },

        new UnitsOfMeasure { Code = "Oz", Id = 66, Name = "Ounce", Description = "Ounce" },
        new UnitsOfMeasure { Code = "YR", Id = 67, Name = "Year", Description = "Year" },
        new UnitsOfMeasure { Code = "M", Id = 68, Name = "Month", Description = "Month" },
        new UnitsOfMeasure { Code = "Wk", Id = 69, Name = "Week", Description = "Week" },
        new UnitsOfMeasure { Code = "D", Id = 70, Name = "Day", Description = "Day" },
        new UnitsOfMeasure { Code = "hr", Id = 71, Name = "Hour", Description = "Hour" },
        new UnitsOfMeasure { Code = "ha", Id = 72, Name = "Hectare", Description = "Hectare" },
        new UnitsOfMeasure { Code = "yd2", Id = 73, Name = "Square yards", Description = "Square yards" },
        new UnitsOfMeasure { Code = "ft2", Id = 74, Name = "Square feet", Description = "Square feet" },
        new UnitsOfMeasure { Code = "cm2", Id = 75, Name = "Square centimetre", Description = "Square centimetre" },
        new UnitsOfMeasure { Code = "m2", Id = 76, Name = "Square metre", Description = "Square metre" },
        new UnitsOfMeasure { Code = "pt", Id = 77, Name = "Pints", Description = "Pints" },
        new UnitsOfMeasure { Code = "qt", Id = 78, Name = "Quarts", Description = "Quarts" },
        new UnitsOfMeasure { Code = "mm", Id = 79, Name = "Millilitre", Description = "Millilitre" },
        new UnitsOfMeasure { Code = "2X", Id = 80, Name = "Meter/Minute", Description = "Meter/Minute" },
        new UnitsOfMeasure { Code = "4G", Id = 81, Name = "Microliter", Description = "Microliter" },

        new UnitsOfMeasure { Code = "4O", Id = 82, Name = "Microfarad", Description = "Microfarad" },
        new UnitsOfMeasure { Code = "4T", Id = 83, Name = "Pikofarad", Description = "Pikofarad" },
        new UnitsOfMeasure { Code = "A", Id = 84, Name = "Ampere", Description = "Ampere" },
        new UnitsOfMeasure { Code = "A87", Id = 85, Name = "Gigaohm", Description = "Gigaohm" },
        new UnitsOfMeasure { Code = "A93", Id = 86, Name = "Gram/Cubic meter", Description = "Gram/Cubic meter" },
        new UnitsOfMeasure { Code = "ACR", Id = 87, Name = "Acre", Description = "Acre" },
        new UnitsOfMeasure
            { Code = "B34", Id = 88, Name = "Kilogram/cubic decimeter", Description = "Kilogram/cubic decimeter" },
        new UnitsOfMeasure { Code = "B45", Id = 89, Name = "Kilomol", Description = "Kilomol" },
        new UnitsOfMeasure { Code = "B47", Id = 90, Name = "Kilonewton", Description = "Kilonewton" },
        new UnitsOfMeasure { Code = "B73", Id = 91, Name = "Meganewton", Description = "Meganewton" },
        new UnitsOfMeasure { Code = "B75", Id = 92, Name = "Megohm", Description = "Megohm" },
        new UnitsOfMeasure { Code = "B78", Id = 93, Name = "Megavolt", Description = "Megavolt" },
        new UnitsOfMeasure { Code = "B84", Id = 94, Name = "Microampere", Description = "Microampere" },
        new UnitsOfMeasure { Code = "BAG", Id = 95, Name = "Bag", Description = "Bag" },

        new UnitsOfMeasure { Code = "BAR", Id = 96, Name = "bar", Description = "bar" },
        new UnitsOfMeasure { Code = "BOT", Id = 97, Name = "Bottle", Description = "Bottle" },
        new UnitsOfMeasure { Code = "BQK", Id = 98, Name = "Becquerel/kilogram", Description = "Becquerel/kilogram" },
        new UnitsOfMeasure { Code = "C10", Id = 99, Name = "Millifarad", Description = "Millifarad" },
        new UnitsOfMeasure { Code = "C36", Id = 100, Name = "Mol per cubic meter", Description = "Mol per cubic meter" },
        new UnitsOfMeasure { Code = "C38", Id = 101, Name = "Mol per liter", Description = "Mol per liter" },
        new UnitsOfMeasure { Code = "C39", Id = 102, Name = "Nanoampere", Description = "Nanoampere" },
        new UnitsOfMeasure { Code = "C3S", Id = 103, Name = "Cubic centimeter/second", Description = "Cubic centimeter/second" },
        new UnitsOfMeasure { Code = "C41", Id = 104, Name = "Nanofarad", Description = "Nanofarad" },
        new UnitsOfMeasure { Code = "C56", Id = 105, Name = "Newton/Square millimeter", Description = "Newton/Square millimeter" },
        new UnitsOfMeasure { Code = "CCM", Id = 106, Name = "Cubic centimeter", Description = "Cubic centimeter" },
        new UnitsOfMeasure { Code = "CD", Id = 107, Name = "Candela", Description = "Candela" },
        new UnitsOfMeasure { Code = "CDM", Id = 108, Name = "Cubic decimeter", Description = "Cubic decimeter" },
        new UnitsOfMeasure { Code = "EA", Id = 109, Name = "Each", Description = "Indicates individual units or items." },
    };
}